# Generated by Django 5.1.3 on 2025-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
