# Generated by Django 5.1.3 on 2025-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_year', models.IntegerField()),
                ('zhanr', models.CharField(choices=[('DR', 'Драма'), ('CO', 'Комедия'), ('TH', 'Триллер'), ('HO', 'Ужасы'), ('AC', 'Боевик'), ('FA', 'Фэнтези')], max_length=2)),
                ('created_at_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
