# Generated by Django 5.1.3 on 2025-03-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='amount',
            new_name='balance',
        ),
    ]
