# Generated by Django 5.1.3 on 2025-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_amount_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
