# Generated by Django 5.1.3 on 2025-03-24 09:19

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_user2'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user2',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
