# Generated by Django 5.1.3 on 2025-03-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_user2_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user2',
            managers=[
            ],
        ),
    ]
